/**
 * Writes `src/styles/builder-safelist.css` from `src/lib/builder/tw-safelist.ts`.
 *
 * Run with: `pnpm generate:tw-safelist` (also runs automatically, see
 * `docs/page-builder.md`, whenever `tw-tokens.ts` or `registry.ts`'s element
 * defaults change — nothing else reads this file's content, so a stale copy
 * is silent until a class an editor picked simply does not render).
 *
 * `pnpm`, not `payload run`: this touches no Payload API, so the plain
 * top-level-await gotcha that catches other scripts here does not apply, and
 * it can run in CI with no database at all.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

import { builderAllClasses } from '../src/lib/builder/tw-safelist.ts'

const dirname = path.dirname(fileURLToPath(import.meta.url))
const outFile = path.resolve(dirname, '../src/styles/builder-safelist.css')

const classes = builderAllClasses()

const banner = `/**
 * GENERATED by scripts/generate-tw-safelist.ts. Do not edit by hand.
 *
 * Every class the page builder can write into a node's \`tw\` bucket
 * (src/lib/builder/tw-safelist.ts), so Tailwind's static scanner generates
 * the CSS for a class name that only ever exists assembled at runtime from
 * a saved document. See that file's own comment for why this exists at all.
 */
`

const body = `@source inline("${classes.join(' ')}");\n`

writeFileSync(outFile, banner + body)

console.log(`Wrote ${classes.length} classes to ${path.relative(process.cwd(), outFile)}`)
