/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Europe/Warsaw';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    authors: Author;
    categories: Category;
    media: Media;
    pages: Page;
    posts: Post;
    subscribers: Subscriber;
    'site-components': SiteComponent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'site-components': SiteComponentsSelect<false> | SiteComponentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'theme-colors': ThemeColor;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'theme-colors': ThemeColorsSelect<false> | ThemeColorsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Konta zespołu i klientów.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Imię i nazwisko lub nazwa widoczna w panelu.
   */
  name?: string | null;
  /**
   * Administrator: pełny dostęp. Moderator: treści i podgląd użytkowników. Redaktor: treści. Klient: bez panelu.
   */
  role: 'administrator' | 'moderator' | 'redaktor' | 'klient';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Autorzy wpisów na blogu, imię, nazwisko, zdjęcie i krótki opis.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Fragment adresu URL (bez ukośników).
   */
  slug: string;
  /**
   * Np. „Fizjoterapeuta", „Trener przygotowania motorycznego".
   */
  role?: string | null;
  photo?: (number | null) | Media;
  bio?: string | null;
  /**
   * Opcjonalnie: tylko jeśli ten autor ma też konto w panelu.
   */
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Biblioteka mediów z polami dostępności/SEO, konwersją formatu i widokiem eksploratora.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Nazwa wyświetlana w bibliotece. Domyślnie z nazwy pliku.
   */
  title?: string | null;
  /**
   * Wymagany dla dostępności i SEO (chyba że dekoracyjny). Uzupełniany z nazwy pliku: sprawdź i popraw.
   */
  alt?: string | null;
  /**
   * Zaznacz, gdy obraz nie niesie informacji (tło, ozdoba). ALT będzie traktowany jako pusty.
   */
  isDecorative?: boolean | null;
  /**
   * Opcjonalny podpis widoczny przy obrazie na stronie.
   */
  caption?: string | null;
  /**
   * Dłuższy opis kontekstu (SEO, redakcja, wyszukiwanie w bibliotece).
   */
  description?: string | null;
  /**
   * Identyfikator URL / nazwy pliku. Domyślnie z nazwy pliku.
   */
  slug?: string | null;
  /**
   * Słowa kluczowe do filtrowania w bibliotece (np. fizjoterapia, sala).
   */
  tags?: string[] | null;
  /**
   * Stosowane przy uploadzie / wymianie pliku. Domyślnie WebP dla obrazów i WebM dla wideo.
   */
  convertFormat?: ('optimized' | 'avif' | 'original') | null;
  /**
   * Skalowanie obrazów przed zapisem (ignorowane dla wideo). 1920 px to dobry kompromis jakość/waga.
   */
  maxDimension?: ('1920' | '1280' | '2560' | 'none') | null;
  /**
   * Dotyczy konwersji WebP / AVIF (ignorowane przy „bez konwersji”).
   */
  imageQuality?: ('balanced' | 'high' | 'small') | null;
  /**
   * Ustawiane automatycznie z MIME; używane do folderów w bibliotece.
   */
  kind?: ('image' | 'video' | 'document' | 'other') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    content?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Kategorie wpisów na blogu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Fragment adresu URL (bez ukośników).
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Struktura witryny: strony można zagnieżdżać (rodzic → dziecko).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Fragment adresu URL (bez ukośników).
   */
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ustaw, aby umieścić stronę w drzewie pod inną stroną.
   */
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tytuł i opis widoczne w wyszukiwarkach oraz przy udostępnianiu w mediach społecznościowych.
   */
  meta?: {
    /**
     * Jeśli puste, użyty zostanie tytuł dokumentu.
     */
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Wpisy na blog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Fragment adresu URL (bez ukośników).
   */
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  publishedAt?: string | null;
  author?: (number | null) | Author;
  /**
   * Wpis może należeć do kilku kategorii: tak jest w obecnym serwisie.
   */
  categories?: (number | Category)[] | null;
  /**
   * Zostaw puste: policzy się automatycznie z długości treści przy zapisie.
   */
  readingMinutes?: number | null;
  /**
   * Tytuł i opis widoczne w wyszukiwarkach oraz przy udostępnianiu w mediach społecznościowych.
   */
  meta?: {
    /**
     * Jeśli puste, użyty zostanie tytuł dokumentu.
     */
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Zapisy do newslettera. Wysyłkę obsługuje Resend, ale lista jest tutaj: status „Potwierdzony” oznacza kliknięcie linku w mailu (wymóg RODO).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  /**
   * Tylko „Potwierdzony” wolno wysyłać. Reszta to brak zgody.
   */
  status: 'pending' | 'confirmed' | 'unsubscribed';
  /**
   * Język, w którym zapisał się subskrybent: do segmentacji wysyłek.
   */
  locale: 'pl' | 'en';
  /**
   * Losowy identyfikator z linków potwierdzenia i wypisu.
   */
  token: string;
  confirmedAt?: string | null;
  unsubscribedAt?: string | null;
  /**
   * Strona, z której przyszedł zapis.
   */
  source?: string | null;
  consentIp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gotowe bloki (przyciski, hero, karuzele, galerie) z własnymi parametrami: do wstawiania na stronach.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-components".
 */
export interface SiteComponent {
  id: number;
  /**
   * Nazwa robocza widoczna tylko w panelu.
   */
  name: string;
  /**
   * Typ decyduje o dostępnych parametrach poniżej.
   */
  type: 'button' | 'hero' | 'carousel' | 'gallery' | 'cta' | 'features';
  /**
   * Napis, odnośnik i wygląd przycisku.
   */
  button?: {
    label?: string | null;
    href?: string | null;
    newTab?: boolean | null;
    variant?: ('solid' | 'outline' | 'ghost' | 'link') | null;
    size?: ('sm' | 'md' | 'lg') | null;
    radius?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
    fullWidth?: boolean | null;
    background?: {
      token?:
        | (
            | 'brand.primary'
            | 'brand.primaryHover'
            | 'brand.secondary'
            | 'brand.secondaryHover'
            | 'brand.accent'
            | 'text.heading'
            | 'text.body'
            | 'text.muted'
            | 'text.inverted'
            | 'text.link'
            | 'text.linkHover'
            | 'surface.page'
            | 'surface.surface'
            | 'surface.surfaceAlt'
            | 'surface.border'
            | 'surface.overlay'
            | 'state.success'
            | 'state.warning'
            | 'state.error'
            | 'state.info'
            | 'custom'
            | 'none'
          )
        | null;
      custom?: string | null;
    };
    textColor?: {
      token?:
        | (
            | 'brand.primary'
            | 'brand.primaryHover'
            | 'brand.secondary'
            | 'brand.secondaryHover'
            | 'brand.accent'
            | 'text.heading'
            | 'text.body'
            | 'text.muted'
            | 'text.inverted'
            | 'text.link'
            | 'text.linkHover'
            | 'surface.page'
            | 'surface.surface'
            | 'surface.surfaceAlt'
            | 'surface.border'
            | 'surface.overlay'
            | 'state.success'
            | 'state.warning'
            | 'state.error'
            | 'state.info'
            | 'custom'
            | 'none'
          )
        | null;
      custom?: string | null;
    };
    /**
     * Używane przy stylu „obramowany”.
     */
    borderColor?: {
      token?:
        | (
            | 'brand.primary'
            | 'brand.primaryHover'
            | 'brand.secondary'
            | 'brand.secondaryHover'
            | 'brand.accent'
            | 'text.heading'
            | 'text.body'
            | 'text.muted'
            | 'text.inverted'
            | 'text.link'
            | 'text.linkHover'
            | 'surface.page'
            | 'surface.surface'
            | 'surface.surfaceAlt'
            | 'surface.border'
            | 'surface.overlay'
            | 'state.success'
            | 'state.warning'
            | 'state.error'
            | 'state.info'
            | 'custom'
            | 'none'
          )
        | null;
      custom?: string | null;
    };
  };
  /**
   * Duże zdjęcie z nagłówkiem, opisem i wezwaniem do działania.
   */
  hero?: {
    image?: (number | null) | Media;
    heading?: string | null;
    subheading?: string | null;
    height?: ('sm' | 'md' | 'lg' | 'screen') | null;
    align?: ('left' | 'center' | 'right') | null;
    /**
     * Kolor nakładki pochodzi z palety (Tła → Przyciemnienie zdjęć).
     */
    overlayOpacity?: number | null;
    radius?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
    textColor?: {
      token?:
        | (
            | 'brand.primary'
            | 'brand.primaryHover'
            | 'brand.secondary'
            | 'brand.secondaryHover'
            | 'brand.accent'
            | 'text.heading'
            | 'text.body'
            | 'text.muted'
            | 'text.inverted'
            | 'text.link'
            | 'text.linkHover'
            | 'surface.page'
            | 'surface.surface'
            | 'surface.surfaceAlt'
            | 'surface.border'
            | 'surface.overlay'
            | 'state.success'
            | 'state.warning'
            | 'state.error'
            | 'state.info'
            | 'custom'
            | 'none'
          )
        | null;
      custom?: string | null;
    };
    /**
     * Wskaż istniejący komponent typu „Przycisk”.
     */
    ctaButton?: (number | null) | SiteComponent;
  };
  /**
   * Przewijane zdjęcia z podpisami: np. galeria gabinetu.
   */
  carousel?: {
    slides?:
      | {
          image: number | Media;
          caption?: string | null;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
    slidesPerView?: ('1' | '2' | '3') | null;
    aspectRatio?: ('16-9' | '21-9' | '4-3' | '1-1' | '3-4') | null;
    radius?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
    gap?: ('none' | 'sm' | 'md' | 'lg') | null;
    autoplay?: boolean | null;
    interval?: number | null;
    showArrows?: boolean | null;
    showDots?: boolean | null;
    loop?: boolean | null;
  };
  /**
   * Siatka zdjęć: realizacje, zespół, wnętrza.
   */
  gallery?: {
    images?: (number | Media)[] | null;
    columns?: ('1' | '2' | '3' | '4') | null;
    gap?: ('none' | 'sm' | 'md' | 'lg') | null;
    aspectRatio?: ('16-9' | '21-9' | '4-3' | '1-1' | '3-4') | null;
    radius?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
    lightbox?: boolean | null;
    /**
     * Podpis pobierany jest z pola „Podpis” w bibliotece mediów.
     */
    showCaptions?: boolean | null;
  };
  /**
   * Wyróżniony pasek z zachętą do kontaktu lub rezerwacji.
   */
  cta?: {
    heading?: string | null;
    text?: string | null;
    align?: ('left' | 'center' | 'right') | null;
    padding?: ('sm' | 'md' | 'lg') | null;
    background?: {
      token?:
        | (
            | 'brand.primary'
            | 'brand.primaryHover'
            | 'brand.secondary'
            | 'brand.secondaryHover'
            | 'brand.accent'
            | 'text.heading'
            | 'text.body'
            | 'text.muted'
            | 'text.inverted'
            | 'text.link'
            | 'text.linkHover'
            | 'surface.page'
            | 'surface.surface'
            | 'surface.surfaceAlt'
            | 'surface.border'
            | 'surface.overlay'
            | 'state.success'
            | 'state.warning'
            | 'state.error'
            | 'state.info'
            | 'custom'
            | 'none'
          )
        | null;
      custom?: string | null;
    };
    textColor?: {
      token?:
        | (
            | 'brand.primary'
            | 'brand.primaryHover'
            | 'brand.secondary'
            | 'brand.secondaryHover'
            | 'brand.accent'
            | 'text.heading'
            | 'text.body'
            | 'text.muted'
            | 'text.inverted'
            | 'text.link'
            | 'text.linkHover'
            | 'surface.page'
            | 'surface.surface'
            | 'surface.surfaceAlt'
            | 'surface.border'
            | 'surface.overlay'
            | 'state.success'
            | 'state.warning'
            | 'state.error'
            | 'state.info'
            | 'custom'
            | 'none'
          )
        | null;
      custom?: string | null;
    };
    radius?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
    button?: (number | null) | SiteComponent;
  };
  /**
   * Zestaw kart z ikoną/zdjęciem, tytułem i krótkim opisem.
   */
  features?: {
    items?:
      | {
          title: string;
          text?: string | null;
          image?: (number | null) | Media;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
    columns?: ('1' | '2' | '3' | '4') | null;
    gap?: ('none' | 'sm' | 'md' | 'lg') | null;
    cardBackground?: {
      token?:
        | (
            | 'brand.primary'
            | 'brand.primaryHover'
            | 'brand.secondary'
            | 'brand.secondaryHover'
            | 'brand.accent'
            | 'text.heading'
            | 'text.body'
            | 'text.muted'
            | 'text.inverted'
            | 'text.link'
            | 'text.linkHover'
            | 'surface.page'
            | 'surface.surface'
            | 'surface.surfaceAlt'
            | 'surface.border'
            | 'surface.overlay'
            | 'state.success'
            | 'state.warning'
            | 'state.error'
            | 'state.info'
            | 'custom'
            | 'none'
          )
        | null;
      custom?: string | null;
    };
    cardBorder?: {
      token?:
        | (
            | 'brand.primary'
            | 'brand.primaryHover'
            | 'brand.secondary'
            | 'brand.secondaryHover'
            | 'brand.accent'
            | 'text.heading'
            | 'text.body'
            | 'text.muted'
            | 'text.inverted'
            | 'text.link'
            | 'text.linkHover'
            | 'surface.page'
            | 'surface.surface'
            | 'surface.surfaceAlt'
            | 'surface.border'
            | 'surface.overlay'
            | 'state.success'
            | 'state.warning'
            | 'state.error'
            | 'state.info'
            | 'custom'
            | 'none'
          )
        | null;
      custom?: string | null;
    };
    titleColor?: {
      token?:
        | (
            | 'brand.primary'
            | 'brand.primaryHover'
            | 'brand.secondary'
            | 'brand.secondaryHover'
            | 'brand.accent'
            | 'text.heading'
            | 'text.body'
            | 'text.muted'
            | 'text.inverted'
            | 'text.link'
            | 'text.linkHover'
            | 'surface.page'
            | 'surface.surface'
            | 'surface.surfaceAlt'
            | 'surface.border'
            | 'surface.overlay'
            | 'state.success'
            | 'state.warning'
            | 'state.error'
            | 'state.info'
            | 'custom'
            | 'none'
          )
        | null;
      custom?: string | null;
    };
    radius?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
  };
  /**
   * Identyfikator używany przy wstawianiu komponentu na stronę.
   */
  slug: string;
  /**
   * Gdzie i po co ten komponent jest używany.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'site-components';
        value: number | SiteComponent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  photo?: T;
  bio?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  isDecorative?: T;
  caption?: T;
  description?: T;
  slug?: T;
  tags?: T;
  convertFormat?: T;
  maxDimension?: T;
  imageQuality?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        content?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  publishedAt?: T;
  author?: T;
  categories?: T;
  readingMinutes?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  locale?: T;
  token?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  source?: T;
  consentIp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-components_select".
 */
export interface SiteComponentsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        variant?: T;
        size?: T;
        radius?: T;
        fullWidth?: T;
        background?:
          | T
          | {
              token?: T;
              custom?: T;
            };
        textColor?:
          | T
          | {
              token?: T;
              custom?: T;
            };
        borderColor?:
          | T
          | {
              token?: T;
              custom?: T;
            };
      };
  hero?:
    | T
    | {
        image?: T;
        heading?: T;
        subheading?: T;
        height?: T;
        align?: T;
        overlayOpacity?: T;
        radius?: T;
        textColor?:
          | T
          | {
              token?: T;
              custom?: T;
            };
        ctaButton?: T;
      };
  carousel?:
    | T
    | {
        slides?:
          | T
          | {
              image?: T;
              caption?: T;
              href?: T;
              id?: T;
            };
        slidesPerView?: T;
        aspectRatio?: T;
        radius?: T;
        gap?: T;
        autoplay?: T;
        interval?: T;
        showArrows?: T;
        showDots?: T;
        loop?: T;
      };
  gallery?:
    | T
    | {
        images?: T;
        columns?: T;
        gap?: T;
        aspectRatio?: T;
        radius?: T;
        lightbox?: T;
        showCaptions?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        text?: T;
        align?: T;
        padding?: T;
        background?:
          | T
          | {
              token?: T;
              custom?: T;
            };
        textColor?:
          | T
          | {
              token?: T;
              custom?: T;
            };
        radius?: T;
        button?: T;
      };
  features?:
    | T
    | {
        items?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              href?: T;
              id?: T;
            };
        columns?: T;
        gap?: T;
        cardBackground?:
          | T
          | {
              token?: T;
              custom?: T;
            };
        cardBorder?:
          | T
          | {
              token?: T;
              custom?: T;
            };
        titleColor?:
          | T
          | {
              token?: T;
              custom?: T;
            };
        radius?: T;
      };
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Tożsamość marki, dane kontaktowe i domyślne SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Paleta motywu stosowana na całej stronie. Kolory trafiają na front jako zmienne CSS (--bw-*).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-colors".
 */
export interface ThemeColor {
  id: number;
  brand?: {
    /**
     * Podstawowy kolor marki (przyciski, aktywne elementy). Zmienna CSS: --bw-primary
     */
    primary?: string | null;
    /**
     * Zmienna CSS: --bw-primary-hover
     */
    primaryHover?: string | null;
    /**
     * Zmienna CSS: --bw-secondary
     */
    secondary?: string | null;
    /**
     * Zmienna CSS: --bw-secondary-hover
     */
    secondaryHover?: string | null;
    /**
     * Wyróżnienia, odznaki, elementy przyciągające wzrok. Zmienna CSS: --bw-accent
     */
    accent?: string | null;
  };
  text?: {
    /**
     * Zmienna CSS: --bw-text-heading
     */
    heading?: string | null;
    /**
     * Zmienna CSS: --bw-text-body
     */
    body?: string | null;
    /**
     * Zmienna CSS: --bw-text-muted
     */
    muted?: string | null;
    /**
     * Używany na przyciskach i sekcjach z ciemnym tłem. Zmienna CSS: --bw-text-inverted
     */
    inverted?: string | null;
    /**
     * Zmienna CSS: --bw-link
     */
    link?: string | null;
    /**
     * Zmienna CSS: --bw-link-hover
     */
    linkHover?: string | null;
  };
  surface?: {
    /**
     * Zmienna CSS: --bw-surface-page
     */
    page?: string | null;
    /**
     * Zmienna CSS: --bw-surface
     */
    surface?: string | null;
    /**
     * Zmienna CSS: --bw-surface-alt
     */
    surfaceAlt?: string | null;
    /**
     * Zmienna CSS: --bw-border
     */
    border?: string | null;
    /**
     * Kolor nakładki na hero i karuzelach (krycie ustawia komponent). Zmienna CSS: --bw-overlay
     */
    overlay?: string | null;
  };
  state?: {
    /**
     * Zmienna CSS: --bw-success
     */
    success?: string | null;
    /**
     * Zmienna CSS: --bw-warning
     */
    warning?: string | null;
    /**
     * Zmienna CSS: --bw-error
     */
    error?: string | null;
    /**
     * Zmienna CSS: --bw-info
     */
    info?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  email?: T;
  phone?: T;
  address?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-colors_select".
 */
export interface ThemeColorsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        primary?: T;
        primaryHover?: T;
        secondary?: T;
        secondaryHover?: T;
        accent?: T;
      };
  text?:
    | T
    | {
        heading?: T;
        body?: T;
        muted?: T;
        inverted?: T;
        link?: T;
        linkHover?: T;
      };
  surface?:
    | T
    | {
        page?: T;
        surface?: T;
        surfaceAlt?: T;
        border?: T;
        overlay?: T;
      };
  state?:
    | T
    | {
        success?: T;
        warning?: T;
        error?: T;
        info?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}